name: Package Game
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PyWeekTubeGame'
          options: --onefile, --name "PyWeekTubeGame", --windowed, 